<?php
namespace hexydec\html;

class comment {

	protected $content = null;

	/**
	 * Parses an array of tokens into an HTML documents
	 *
	 * @param array &$tokens An array of tokens generated by tokenise()
	 * @param array $config An array of configuration options
	 * @return bool Whether the parser was able to capture any objects
	 */
	public function parse(array &$tokens) {
		$token = current($tokens);
		$this->content = mb_substr($token['value'], 4, -3);
	}

	/**
	 * Minifies the internal representation of the comment
	 *
	 * @param array $minify An array of minification options controlling which operations are performed
	 * @return void
	 */
	public function minify(array $minify) {
		if ($minify['comments'] && (empty($minify['comments']['ie']) || (mb_strpos($this->content, '[if ') !== 0 && $this->content != '<![endif]'))) {
			$this->content = null;
		}
	}

	/**
	 * Compile the comment as an HTML string
	 *
	 * @param array $options An array indicating output options
	 * @return string The compiled HTML
	 */
	public function html(array $options = null) : string {
		return $this->content === null ? '' : '<!--'.$this->content.'-->';
	}
}
