<?php
namespace hexydec\html;

class script {

	/**
	 * @var htmldoc The parent htmldoc object
	 */
	protected $root;

	/**
	 * @var string A string containing javascript
	 */
	protected $content = null;

	/**
	 * Constructs the script object
	 *
	 * @param htmldoc $root The parent htmldoc object
	 */
	public function __construct(htmldoc $root) {
		$this->root = $root;
	}

	/**
	 * Parses an array of tokens into an HTML documents
	 *
	 * @param array &$tokens An array of tokens generated by tokenise()
	 * @param array $config An array of configuration options
	 * @return bool Whether the parser was able to capture any objects
	 */
	public function parse(array &$tokens) {
		$value = '';
		$token = current($tokens);
		$quotes = 0;
		while ($token !== false && ($quotes % 2 || $token['type'] != 'tagclose' || $token['value'] != '</script>')) {
			$value .= $token['value'];

			// count quotes so we don't capture a script tag in a string
			$quotes += substr_count(str_replace(['\\\\', '\\\\"', "\\\\'"], ['', '', ''], $token['value']), '"');
			$token = next($tokens);
		}
		prev($tokens);
		if ($value) {
			$this->content = $value;
		}
	}

	/**
	 * Minifies the internal representation of the script using an external minifier
	 *
	 * @param array $minify An array of minification options controlling which operations are performed
	 * @return void
	 */
	public function minify(array $minify) {
		if ($minify['js'] !== false && $this->content) {
			$func = $this->root->getConfig('js');
			$this->content = $func === false ? trim($this->content) : call_user_func($func, $this->content, $minify['js']);
		}
	}

	public function html() {
		return $this->content;
	}

	public function __get($var) {
		return $this->$var;
	}
}
