<?php
declare(strict_types = 1);
namespace hexydec\html;

class style implements token {

	/**
	 * @var htmldoc The parent htmldoc object
	 */
	protected $root;

	/**
	 * @var string A string containing CSS styles
	 */
	protected $content = '';

	/**
	 * Constructs the style object
	 *
	 * @param htmldoc $root The parent htmldoc object
	 */
	public function __construct(htmldoc $root) {
		$this->root = $root;
	}

	/**
	 * Parses an array of tokens into an HTML documents
	 *
	 * @param array &$tokens An array of tokens generated by tokenise()
	 * @param array $config An array of configuration options
	 * @return void
	 */
	public function parse(tokenise $tokens) : void {
		if (($token = $tokens->current()) !== null) {
			$value = '';
			while ($token !== null && ($token['type'] != 'tagclose' || $token['value'] != '</style>')) {
				if ($token['type'] == 'cdata') {
					$value .= mb_substr($token['value'], 9, -3);
				} else {
					$value .= $token['value'];
				}
				$token = $tokens->next();
			}
			$tokens->prev();
			if ($value) {
				$this->content = $value;
			}
		}
	}

	/**
	 * Minifies the internal representation of the styles using an external minifier
	 *
	 * @param array $minify An array of minification options controlling which operations are performed
	 * @return void
	 */
	public function minify(array $minify) : void {
		if (!isset($minify['style']) || $minify['style'] !== false) {
			$this->content = trim($this->content);
			if ($this->content) {
				$func = $this->root->getConfig('custom', 'style', 'config', 'minifier');
				if ($func) {
					$this->content = call_user_func($func, $this->content, $minify['style']);
				}
			}
		}
	}

	/**
	 * Compile the styles as an HTML string
	 *
	 * @param array $options An array indicating output options
	 * @return string The compiled HTML
	 */
	public function html(array $options = []) : string {
		return $options['xml'] ? '<![CDATA['.$this->content.']]>' : $this->content;
	}
}
