<?php
namespace hexydec\html;

class style {

	protected $content = null;

	/**
	 * Parses an array of tokens into an HTML documents
	 *
	 * @param array &$tokens An array of tokens generated by tokenise()
	 * @param array $config An array of configuration options
	 * @return bool Whether the parser was able to capture any objects
	 */
	public function parse(array &$tokens) {
		$value = '';
		$token = current($tokens);
		while ($token !== false && ($token['type'] != 'tagclose' || $token['value'] != '</style>')) {
			$value .= $token['value'];
			$token = next($tokens);
		}
		prev($tokens);
		if ($value) {
			$this->content = $value;
		}
	}

	public function minify(array $minify) {
		if ($minify['css'] && $this->content) {
			$this->content = $minify['css'] === true ? trim($this->content) : call_user_func($minify['css'], $this->content);
		}
	}

	public function html(Array $config) {
		return $this->content;
	}

	public function __get($var) {
		return $this->$var;
	}
}
