<?php
declare(strict_types = 1);
namespace hexydec\css;

class directive {

	/**
	 * @var rule The parent rule object
	 */
	protected $root;

	/**
	 * @var string The name of the directive
	 */
	protected $directive;

	/**
	 * @var string The value of the directive
	 */
	protected $content = null;

	/**
	 * @var array An array of properties
	 */
	protected $properties = [];

	/**
	 * Constructs the comment object
	 *
	 * @param cssdoc $root The parent htmldoc object
	 */
	public function __construct(mediaquery $root) {
		$this->root = $root;
	}

	/**
	 * Parses an array of tokens into an HTML documents
	 *
	 * @param array &$tokens An array of tokens generated by tokenise()
	 * @param array $config An array of configuration options
	 * @return void
	 */
	public function parse(array &$tokens) : void {
		$directive = true;
		$token = current($tokens);
		do {
			switch ($token['type']) {
				case 'directive':
					$this->directive = $token['value'];
					break;
				case 'string':
				case 'quotes':
					if ($directive) {
						$this->content = $token['value'];
					} else {
						$item = new property($this);
						$item->parse($tokens);
						$this->properties[] = $item;
					}
					break;
				case 'curlyopen':
					$directive = false;
					break;
				case 'semicolon':
				case 'curlyclose':
					break 2;
			}
		} while (($token = next($tokens)) !== false);
	}

	/**
	 * Minifies the internal representation of the comment
	 *
	 * @param array $minify An array of minification options controlling which operations are performed
	 * @return void
	 */
	public function minify(array $minify) : void {
	}

	/**
	 * Compile the property to a string
	 *
	 * @param array $options An array of compilation options
	 * @return void
	 */
	public function compile(array $options) : string {
		$b = $options['output'] != 'minify';
		$css = $this->directive;
		if ($this->content) {
			$css .= ' '.$this->content;
		}
		if ($this->properties) {
			$css .= $b ? ' {' : '{';

			// compile properties
			$tab = $b ? "\n\t" : '';
			foreach ($this->properties AS $item) {
				$css .= $tab.$item->compile($options);
			}
			$css .= $b ? "\n".$options['prefix'].'}' : '}';
		} else {
			$css .= ';';
		}
		return $css;
	}
}
