<?php
declare(strict_types = 1);
namespace hexydec\css;

class property {

	/**
	 * @var rule The parent rule object
	 */
	protected $root;

	/**
	 * @var string The name of the property
	 */
	protected $name;

	/**
	 * @var string The value of the property
	 */
	protected $value;

	/**
	 * @var bool Whether the property is important
	 */
	protected $important = false;

	protected $semicolon = true;

	protected $comment = null;

	/**
	 * Constructs the comment object
	 *
	 * @param cssdoc $root The parent htmldoc object
	 */
	public function __construct(rule $root) {
		$this->root = $root;
	}

	/**
	 * Parses an array of tokens into an HTML documents
	 *
	 * @param array &$tokens An array of tokens generated by tokenise()
	 * @param array $config An array of configuration options
	 * @return void
	 */
	public function parse(array &$tokens) : void {
		while (($token = next($tokens)) !== false) {
			if ($token['type'] == 'string') {
				$prop = $token['value'];
				while (($token = next($tokens)) !== false) {
					switch ($token['type']) {
						case 'colon':
							$important = false;
							if (($value = $this->parsePropertyValue($tokens, $important, $comment)) !== null) {
								$this->name = $prop;
								$this->value = $value;
								$this->important = $important;
								$this->comment = $comment;
							}
							break;
						case 'semicolon':
							$this->semicolon = true;
						case 'curlyclose':
							break 3;
					}
				}
			}

			// end rule
			if ($token['type'] == 'curlyclose') {
				prev($tokens);
				break;
			}
		}
	}

	protected function parsePropertyValue(array &$tokens, bool &$important = false, string &$comment = null) : ?array {
		$properties = [];
		$values = [];
		$important = false;
		$comment = null;
		while (($token = next($tokens)) !== false) {
			switch ($token['type']) {
				case 'string':
					if ($token['value'] == '!important') {
						$important = true;
					} else {
						$values[] = $token['value'];
					}
					break;
				case 'comma':
					$properties[] = $values;
					$values = [];
					break;
				case 'bracketopen':
					$values[] = self::parsePropertyValue($tokens);
					break;
				case 'comment':
					$comment = $token['value'];
					break;
				case 'bracketclose':
				case 'semicolon':
				case 'curlyclose':
					prev($tokens);
					break 2;
			}
		}
		if ($values) {
			$properties[] = $values;
		}
		return $properties ? $properties : null;
	}

	/**
	 * Minifies the internal representation of the comment
	 *
	 * @param array $minify An array of minification options controlling which operations are performed
	 * @return void
	 */
	public function minify(array $minify) : void {
	}

	/**
	 * Compile the property to a string
	 *
	 * @param array $options An array of compilation options
	 * @return void
	 */
	public function compile(array $options) : string {
		$b = $options['output'] != 'minify';
		$css = $this->name.':'.($b ? ' ' : '');
		$join = '';
		foreach ($this->value AS $value) {
			$space = '';
			foreach ($value AS $item) {
				if (is_array($item)) {

				} else {
					$css .= $space.$item;
				}
				$space = ' ';
			}
			$css .= $join;
			$join = $b ? ', ' : ',';
		}
		if ($this->semicolon) {
			$css .= ';';
		}
		return $css;
	}
}
